### PR TITLE
closes #8: adds the targets-user-text-objects user option

### LINKED ISSUE #8: what is the cleanest way to customize single elements in the targets-pair-text-objects list?
hi @noctuid. I'm using this package 24/7 to great success. It is awesome already. I don't miss a thing from [wellle/targets.vim](http://github.com/wellle/targets.vim)

I like to use `b` instead of `(` for the round bracket text object. So I've setup my targets.el like so:

```elisp
(use-package targets :load-path "lisp/noctuid/targets.el"
    :init
    (setq targets-separator-text-objects '())

    (add-to-list 'targets-separator-text-objects
                 '(pipe "|" nil separator))

    (setq targets-pair-text-objects
          '((paren "(" ")" pair :more-keys "b")
            (bracket "[" "]" pair :more-keys "r")
            (curly "{" "}" pair :more-keys "c")
            (angle "<" ">" pair)))
    :config
    (targets-setup t))
```

But I'm nervous that new text objects could be added/removed. Is there a cleaner way to alias the `(` text object than what I'm using? 

Thanks!

### PR DESCRIPTION
**Pull request by ninrod**
@noctuid, this is my newbie take on implementing the `targets-user-text-objects` option.

I'm using this with success with the following snippet:

```elisp
(use-package avy :ensure t)
  (with-eval-after-load "avy"
    (use-package targets :load-path "lisp/ninrod/targets.el"
      :init
      (setq targets-user-text-objects '((pipe "|" nil separator)
                                        (paren "(" ")" pair :more-keys "b")
                                        (bracket "[" "]" pair :more-keys "r")
                                        (curly "{" "}" pair :more-keys "c")))
      :config
      (targets-setup t
                     :inside-key nil
                     :around-key nil
                     :remote-key nil)))
```

I should point out that this is my very first serious elisp assignment and I've found that programming in elisp is actually fun and productive.

### CODE REVIEW

**Comment by noctuid** [comment]
Thanks for the pull request. The changes to the README look good, but a couple things in the code could be changed.

The main thing is that I'd like the lists to be merged in `targets-setup`. Merging them in the defvar requires the user to set `targets-user-text-objects` before loading targets. If they are merged in `targets-setup`, the user can change `targets-user-text-objects` at any time and then run `targets-setup` again.

The other thing is that while the code you wrote to merge the lists was probably better for learning, I'd rather `cl-union` be used (with `:test` specified) since it is higher level of abstraction and would make the code simpler (no new functions necessary).

As a minor nitpick, please hard wrap the docstring at col 80. It would also be nice to mention `targets-text-objects` in the `targets-user-text-object` docstring:
```elisp
(defvar targets-user-text-objects nil
  "User defined text objects. These take precedence over text objects in
`targets-text-objects'.")
```


Some comments on the code that may be useful when writing elisp in the future:

`dolist` will return nil if you don't specify the RESULT, so the extra nil at the end isn't needed.

For iteration macros like `dolist` and `dotimes`, `cl-lib` has equivalents (e.g. `cl-dolist` and `cl-dotimes`) that will wrap the body in a nil block. `cl-defun` works fine for this, but you could also do `(cl-return-from nil t)` if you used `cl-dolist`. This would be useful if you wanted to exit a loop but not the entire function.

`(append list nil)` is the same as `list`. It's not necessary here, but in the rare case you need to copy a list, you can use `cl-copy-list`.

**Comment by ninrod** [comment]
wow! Ok, that's a lot of information. I'll try to make the adjustments.

**Comment by ninrod** [comment]
@noctuid, 17f0bb0 should address your first [point](https://github.com/ninrod/targets.el/issues/1)

**Comment by ninrod** [comment]
@noctuid, looking at the documentation [here](https://www.gnu.org/software/emacs/manual/html_node/cl/Lists-as-Sets.html) and trying out in the lisp interaction mode, I was not able to find a way to express exactly what my newbie code does. 

this looked promising:

```elisp
(cl-union targets-user-text-objects
          targets-pair-default
          :key #'car)
```

but there is no way to implement (that I could find, to the best of my ability) a `:test` function that says to cl-union to pick targets-pair-default only if it is not present in targets-user-text-objects for unequal list sizes. 

I'm kind of lost here.

edit this snippet:

```elisp
(cl-union default-frutas
          user-frutas
          :key #'car
          :test (lambda (e1 e2)
                  (message "e1 = %s, e2 = %s" e1 e2)
                  nil))
```

prints only one message. since I'm returning false, `cl-union` will select both ocurrences of, e.g., `paren`. If I return true, `cl-union` will pick whatever it likes.

**Comment by noctuid** [comment]
My bad, that would be correct, but unlike `-union`, `cl-union` doesn't define which list it will take the item from in the case where it is in both. You can use whatever other method you like (e.g. `append` and `cl-remove-duplicates` or `append` and `cl-set-difference`).

**Comment by ninrod** [comment]
Ok, this:

```elisp
(cl-defun targets--optlist-contains (list seek)
  "Verify if SEEK is inside LIST."
  (dolist (element list)
    (when (eq seek (car element))
      (cl-return-from targets--optlist-contains t))))

(defun targets--merge-list (userlist defaultlist)
  "Create a new list.  Merge between USERLIST and DEFAULTLIST."
  (let ((mergedlist userlist))
    (dolist (element defaultlist mergedlist)
      (unless (targets--optlist-contains userlist (car element))
        (setq mergedlist (cons element mergedlist))))))
```

can be rewritten to this:

```elisp
(defun targets--merge-v2 (userlist defaultlist)
  "new try!"
  (append userlist (cl-set-difference defaultlist userlist :key #'car)))
```
talk about less lines of code.

**Comment by ninrod** [comment]
There, @noctuid. Could you review? I think I've managed to implement all your listed points.

**Comment by noctuid** [comment]
Could you make the change I suggested to the `targets-user-text-objects` docstring? Also, could you not alter the `targets-default-text-object` docstring (the indentation shouldn't be there, but the change is not related to this commit). Thanks.

**Comment by ninrod** [comment]
Certainly. Are the docstrings correct now?

**Comment by noctuid** [comment]
It looks like it. Could you squash the commits?

**Comment by ninrod** [comment]
Sure thing. Done.

**Comment by noctuid** [comment]
Alright, thanks!

**Pull request merged**
